Add collection-level pre-request script
PlayFab/PostmanCollection pull request #62
Opened 2020-09-16 02:28 UTC by marc-young-msft

Add collection-level pre-request script that automatically fetches and saves an entity token for future calls.

2020-09-29 21:00 UTC, pgilmorepf requested changes
I'm "requesting changes" because this PR must be converted/moved over to the template, rather than here.
The PR looks good, except that I need to move it into the other place.

Can you reply to my comment about global vs environment before we move it?
Maybe it could check both global AND environment?

2020-09-29 21:00 UTC, pgilmorepf commented on playfab.json
> +					"var autoTitleToken = pm.globals.get(\"PlayFab_AutoTitleToken\");",
I think I'd rather the toggle be per-environment rather than a global.
```suggestion
					"var autoTitleToken = pm.environment.get(\"PlayFab_AutoTitleToken\");",
```

2020-10-01 17:38 UTC, marc-young-msft commented on playfab.json
> +					"var autoTitleToken = pm.globals.get(\"PlayFab_AutoTitleToken\");",
I liked your suggestion to allow either a global or environment variable.

2020-11-19 23:03 UTC, pgilmorepf commented
I'm gonna close this PR, but note your PR was accepted and processed here:
https://github.com/PlayFab/SDKGenerator/commit/9ed9356967363871af4b4c110a67e5ceacdfdc91
Thanks!

2020-11-19 23:03 UTC, closed without merging